# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 322f007b20122750a81e2596f70466cc5c91ce0558f5cd89d308dfa7b70f6e243a8368581e769da878c1a273bcfa1d6ac1dc4f3004417515982d88962e26ef1e

test:
  secret_key_base: 64e6d413010c138749aa925a7d8892dee695198458fdba7758105e2f2f7d4b4123aa7b6622c91f22fa93d9475b9e32fe9628fce67aa8a103e16541470f322c9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
